FROM golang:1.22-alpine

WORKDIR /app

# Копируем модули и скачиваем зависимости
COPY triple-s/go.mod ./
RUN go mod download

# Копируем исходники triple-s
COPY triple-s/*.go ./

# Собираем приложение
RUN go build -o triple-s

# Создаем директорию для данных
RUN mkdir -p /data

# Запускаем сервис
CMD ["./triple-s", "--port", "8082", "--dir", "/data"]

EXPOSE 8082